export const EMOTIONS_HIERARCHY: Record<string, Record<string, string[]>> = {
  "Alegría": {
    "Optimismo": ["Bromista", "Jueguetón"],
    "Poder": ["Provocación", "Valentía"],
    "Orgullo": ["Presuntuoso", "Importante"],
    "Creatividad": ["Inspiración", "Ingenio"],
    "Ilusión": ["Esperanza", "Expectación"],
    "Interés": ["Entretenimiento", "Curiosidad"],
    "Euforia": ["Liberación", "Exhaltación"]
  },
  "Calma": {
    "Concentración": ["Contemplación", "Atención"],
    "Tranquilidad": ["Relajación", "Serenidad"],
    "Seguridad": ["Aceptación", "Respeto"],
    "Agradecimiento": ["Compasión", "Autocompasión"],
    "Plenitud": ["Satisfacción", "Placidez"],
    "Pacífico": ["Dulzura", "Comprensión"],
    "Conexión": ["Armonía", "Fluir"],
    "Paz interior": ["Equilibrio", "Dicha"]
  },
  "Tristeza": {
    "Culpable": ["Arrepentimiento", "Vergüenza"],
    "Abandono": ["Ignorado", "Victimizado"],
    "Desesperación": ["Desvalido", "Vulnerable"],
    "Decaimiento": ["Melancolía", "Vacío"],
    "Pena": ["Desamparo", "Abatimiento"],
    "Apatía": ["Aburrimiento", "Indiferente"]
  },
  "Asco": {
    "Disconforme": ["Moralista", "Reacio"],
    "Decepción": ["Repugnante", "Engañado"],
    "Horrible": ["Asco", "Odioso"],
    "Abstinencia": ["Aversión", "Vacilante"]
  },
  "Ira": {
    "Herido": ["Devastación", "Destrozo"],
    "Amenazado": ["Celos", "Atascado"],
    "Odio": ["Traición", "Resentimiento"],
    "Locura": ["Rabia", "Furia"],
    "Agresividad": ["Provocación", "Hostil"],
    "Frustración": ["Impaciencia", "Irritación"],
    "Distante": ["Suspicacia", "Desconfianza"],
    "Crítico": ["Escepticismo", "Sarcasmo"]
  },
  "Miedo": {
    "Envidia": ["Comparación", "Recelo"],
    "Susto": ["Espanto", "Terror"],
    "Ansiedad": ["Preocupación", "Agobio"],
    "Inseguridad": ["Inferior", "Insuficiente"],
    "Sumisión": ["Insignificante", "Inútil"],
    "Rechazo": ["Alienación", "Marginación"],
    "Humillación": ["Ridículo", "Desprecio"]
  },
  "Sorpresa": {
    "Sorprendido": ["Conmoción", "Alucinar"],
    "Confusión": ["Desilusión", "Perplejidad"],
    "Asombro": ["Estupefacción", "Impresión"],
    "Entusiasmo": ["Entusiasta", "Enérgico"]
  }
};

export const EMOTIONS_DESCRIPTIONS: Record<string, string> = {
  "Alegría": "Estado emocional positivo, caracterizado por una sensación de bienestar, vitalidad y satisfacción general.",
  "Optimismo": "Disposición mental orientada a esperar resultados positivos o favorables del futuro.",
  "Bromista": "Expresión lúdica y humorística orientada a generar risa o distensión en el entorno social.",
  "Jueguetón": "Disposición activa hacia el disfrute, la exploración sin presiones y la interacción recreativa.",
  "Poder": "Sensación de control, eficacia y capacidad para influir en el entorno propio o ajeno.",
  "Provocación": "Estímulo intencional hacia otros para generar una reacción, a menudo como demostración de seguridad.",
  "Valentía": "Capacidad psicológica de afrontar situaciones adversas o peligrosas a pesar de experimentar temor.",
  "Orgullo": "Satisfacción derivada de los propios logros, habilidades o de la asociación con aspectos valorados positivamente.",
  "Presuntuoso": "Manifestación exagerada del orgullo, proyectando superioridad ante los demás de forma ostentosa.",
  "Importante": "Sensación de valía personal y reconocimiento de la propia relevancia en un contexto social.",
  "Creatividad": "Estado cognitivo de fluidez y flexibilidad mental que facilita la asociación novedosa de ideas.",
  "Inspiración": "Estado de activación y claridad mental que impulsa la acción creativa y la motivación intrínseca.",
  "Ingenio": "Capacidad de respuesta mental ágil y perspicaz, a menudo asociada con la resolución rápida de problemas.",
  "Ilusión": "Anticipación placentera y motivadora respecto a un evento futuro deseado.",
  "Esperanza": "Creencia sostenida de que un resultado positivo es posible, incluso en circunstancias inciertas.",
  "Expectación": "Estado de vigilancia cognitiva y emocional ante la inminencia de un acontecimiento significativo.",
  "Interés": "Estado de activación atencional y motivación enfocada hacia un estímulo o tema particular.",
  "Entretenimiento": "Estado de gratificación y absorción atencional derivado de actividades lúdicas o narrativas.",
  "Curiosidad": "Impulso intrínseco por buscar nueva información, explorar y cerrar brechas de conocimiento.",
  "Euforia": "Estado de alegría extrema y exaltación, a menudo acompañado de hiperactividad motora y cognitiva.",
  "Liberación": "Sensación de alivio profundo y expansión emocional tras la eliminación de una carga o represión.",
  "Exhaltación": "Emoción intensa de triunfo, júbilo o entusiasmo desbordante.",
  "Calma": "Estado de baja activación fisiológica y equilibrio emocional, libre de agitación o estrés significativo.",
  "Concentración": "Enfoque sostenido e intencional de la atención sobre un único estímulo, pensamiento o tarea.",
  "Contemplación": "Observación atenta y serena, generalmente acompañada de reflexión profunda y no reactiva.",
  "Atención": "Estado de alerta focalizada y receptividad hacia la información del entorno o interna.",
  "Tranquilidad": "Sensación de quietud mental y relajación corporal, sin preocupaciones inminentes.",
  "Relajación": "Disminución deliberada de la tensión física y psicológica, restaurando el equilibrio basal.",
  "Serenidad": "Estado de paz interior perdurable, caracterizado por la imperturbabilidad ante estímulos externos.",
  "Seguridad": "Ausencia de miedo o ansiedad frente a amenazas potenciales, basada en la confianza interna o externa.",
  "Aceptación": "Recepción consciente y sin juicio de la realidad, los propios estados o de los demás.",
  "Respeto": "Reconocimiento y valoración de la dignidad intrínseca, límites y derechos propios o ajenos.",
  "Agradecimiento": "Reconocimiento emocional profundo por un beneficio o bienestar recibido de una fuente externa o interna.",
  "Compasión": "Sensibilidad empática ante el sufrimiento ajeno acompañada del deseo genuino de aliviarlo.",
  "Autocompasión": "Disposición de tratarte a ti mismo con cuidado, comprensión y apoyo frente al fracaso o dolor.",
  "Plenitud": "Sensación de satisfacción global donde las necesidades psicológicas y existenciales están colmadas.",
  "Satisfacción": "Estado de agrado derivado del cumplimiento de metas, deseos o expectativas.",
  "Placidez": "Estado de sosiego y suavidad emocional, sin turbulencias ni exigencias inminentes.",
  "Pacífico": "Disposición armónica y conciliadora que rechaza el conflicto o la agresión.",
  "Dulzura": "Expresión tierna, afectuosa y considerada hacia el entorno, reflejando amabilidad interior.",
  "Comprensión": "Capacidad empática de captar y acoger intelectual y emocionalmente la perspectiva ajena.",
  "Conexión": "Sentimiento profundo de vinculación significativa con otras personas, la naturaleza o el propósito.",
  "Armonía": "Percepción de coherencia, orden y resonancia positiva entre diferentes elementos o individuos.",
  "Fluir": "Estado de absorción total en una actividad donde se pierde la noción del tiempo y el ego.",
  "Paz interior": "Estado espiritual y psicológico de equilibrio profundo, independiente de las circunstancias externas.",
  "Equilibrio": "Estabilidad emocional donde las demandas externas e internas se gestionan sin perturbación.",
  "Dicha": "Estado prolongado de alegría tranquila y contentamiento existencial profundo.",
  "Tristeza": "Reacción emocional ante la pérdida, la decepción o la frustración, caracterizada por baja energía y repliegue social.",
  "Culpable": "Sentimiento aversivo derivado de la evaluación de haber transgredido un estándar moral o personal.",
  "Arrepentimiento": "Dolor moral por una acción u omisión pasada, acompañado del deseo de enmendarla o no haberla cometido.",
  "Vergüenza": "Emoción dolorosa ligada a la percepción de tener un defecto o insuficiencia que nos deshonra ante los demás.",
  "Abandono": "Sensación de desamparo, pérdida de apoyo afectivo y aislamiento forzado.",
  "Ignorado": "Percepción dolorosa de ser invisible, excluido o irrelevante para los demás.",
  "Victimizado": "Sentimiento de haber sufrido un daño injusto, acompañado de impotencia e indefensión.",
  "Desesperación": "Pérdida total de la esperanza respecto a la resolución de una situación dolorosa o amenazante.",
  "Desvalido": "Percepción de incapacidad absoluta para protegerse o proveer para uno mismo.",
  "Vulnerable": "Conciencia angustiosa de estar expuesto al daño emocional o físico sin defensas suficientes.",
  "Decaimiento": "Descenso marcado de la vitalidad física y anímica, con falta de motivación o interés general.",
  "Melancolía": "Estado de tristeza profunda y añoranza, a menudo reflexiva y ligada a recuerdos idealizados del pasado.",
  "Vacío": "Sensación psicológica de falta de propósito, conexión o significado en la propia existencia.",
  "Pena": "Dolor emocional agudo causado por una pérdida significativa, como un duelo o un rechazo profundo.",
  "Desamparo": "Sentimiento de soledad y privación de auxilio en circunstancias adversas o dolorosas.",
  "Abatimiento": "Colapso del ánimo y las fuerzas frente a la pesadumbre o una decepción contundente.",
  "Apatía": "Estado de embotamiento afectivo, indiferencia y falta prolongada de emoción o motivación.",
  "Aburrimiento": "Estado aversivo de falta de estimulación, donde el entorno no logra captar ni mantener la atención.",
  "Indiferente": "Desconexión emocional y ausencia de interés o reactividad ante eventos que normalmente provocarían una respuesta.",
  "Asco": "Reacción emocional de rechazo profundo hacia algo percibido como física o moralmente repugnante o contaminante.",
  "Disconforme": "Rechazo moderado y evaluación negativa hacia una idea, situación o comportamiento.",
  "Moralista": "Rechazo basado en juicios estrictos de valor y la percepción de transgresiones éticas por parte de otros.",
  "Reacio": "Resistencia activa, disgusto y falta de disposición para aceptar o participar en algo.",
  "Decepción": "Sentimiento de caída anímica derivado del incumplimiento de una expectativa o promesa sobre algo o alguien.",
  "Repugnante": "Reacción de asco extremo que puede inducir evitación física inmediata ante un estímulo nocivo.",
  "Engañado": "Sensación de desilusión y rechazo tras descubrir una falsedad, traición o manipulación deliberada.",
  "Horrible": "Percepción de algo como inaceptablemente malo, espantoso y repulsivo en su naturaleza.",
  "Odioso": "Rechazo y antipatía intensos hacia algo o alguien que provoca un gran nivel de molestia o aversión visceral.",
  "Abstinencia": "Rechazo a participar, a menudo por repulsión emocional o preservación de la propia integridad.",
  "Aversión": "Asco prolongado y profundo que genera un deseo constante de apartarse o rechazar un estímulo específico.",
  "Vacilante": "Disposición dubitativa y resistente a acercarse o interactuar debido a la percepción de algo desagradable o contaminado.",
  "Ira": "Respuesta emocional agresiva o defensiva ante la percepción de una amenaza, ofensa, frustración o injusticia.",
  "Herido": "Estado emocional de dolor profundo que se traduce en hostilidad como mecanismo de defensa y autoprotección.",
  "Devastación": "Reacción de furia y dolor abrumadores ante una pérdida drástica o un ataque crítico a la integridad personal.",
  "Destrozo": "Sentimiento de quebrantamiento interno que se externaliza a través de ira irracional y destructiva.",
  "Amenazado": "Alerta agresiva activada por la percepción de un peligro inminente que atenta contra uno mismo o lo que se valora.",
  "Celos": "Ira mezclada con ansiedad ante la amenaza de perder una relación o recurso valioso a manos de un rival.",
  "Atascado": "Frustración intensa y agresiva por la incapacidad de avanzar, percibiéndose bloqueado por circunstancias externas.",
  "Odio": "Aversión profunda, hostilidad persistente y deseo de dañar o destruir a la persona o entidad percibida como ofensiva.",
  "Traición": "Furia aguda originada en la ruptura maliciosa de la confianza por parte de alguien significativo.",
  "Resentimiento": "Ira crónica y silenciosa, acumulada por agravios pasados percibidos como injustos y no resueltos.",
  "Locura": "Estado extremo de descontrol emocional donde la ira nubla la racionalidad y el juicio crítico.",
  "Rabia": "Manifestación explosiva y desproporcionada de ira que busca confrontación inmediata o destrucción.",
  "Furia": "Estado de máxima cólera, a menudo con pérdida de control inhibitorio y gran activación motora.",
  "Agresividad": "Disposición proactiva hacia el conflicto o el ataque, como forma de dominio o defensa asertiva exagerada.",
  "Hostil": "Actitud sostenida de enemistad, oposición y malevolencia oculta o manifiesta hacia el entorno.",
  "Frustración": "Emoción negativa originada por la interferencia o el bloqueo sistemático en la consecución de una meta.",
  "Impaciencia": "Irritabilidad causada por la intolerancia a la demora o al ritmo lento de los acontecimientos.",
  "Irritación": "Molestia superficial pero persistente ante estímulos que resultan recurrentemente desagradables o inoportunos.",
  "Distante": "Forma fría y calculada de ira, expresada a través de la retirada del afecto y el aislamiento punitivo.",
  "Suspicacia": "Ira enmascarada de desconfianza cautelosa, anticipando intenciones maliciosas u ocultas en los demás.",
  "Desconfianza": "Actitud defensiva y oposicional sostenida por la expectativa de ser dañado o manipulado.",
  "Crítico": "Expresión cognitiva de la ira a través de juicios severos, condenas y evaluaciones negativas hacia los demás.",
  "Escepticismo": "Ira intelectualizada que se manifiesta rechazando sistemáticamente la validez o buenas intenciones de otros.",
  "Sarcasmo": "Agresión verbal indirecta que utiliza la ironía mordaz para humillar, atacar o expresar desdén.",
  "Miedo": "Respuesta de alarma fisiológica y psicológica ante un peligro o amenaza percibida que atenta contra la propia seguridad física o psicológica.",
  "Envidia": "Dolor y miedo a la inferioridad originado por el deseo de poseer los atributos, logros o posesiones de otro.",
  "Comparación": "Miedo sistemático a no estar a la altura que lleva a medir el propio valor en función de los logros ajenos.",
  "Recelo": "Temor suspicaz que advierte sobre posibles amenazas a los propios intereses por parte de personas o circunstancias inciertas.",
  "Susto": "Reacción aguda de sobresalto y alarma ante un estímulo repentino e inesperado percibido como peligroso.",
  "Espanto": "Miedo intenso y paralizante ante algo percibido como grotesco, amenazador o incomprensiblemente terrorífico.",
  "Terror": "Grado extremo y abrumador del miedo que causa desorganización cognitiva y una respuesta de lucha, huida o parálisis total.",
  "Ansiedad": "Estado de inquietud y expectación temerosa ante amenazas futuras, difusas o inciertas, acompañado de tensión somática.",
  "Preocupación": "Proceso cognitivo repetitivo centrado en anticipar eventos negativos y rumiar sobre posibles escenarios catastróficos.",
  "Agobio": "Ansiedad intensa caracterizada por la percepción de que las demandas internas o externas superan abrumadoramente los propios recursos de afrontamiento.",
  "Inseguridad": "Falta generalizada de confianza en la propia valía, capacidad o legitimidad en distintas áreas de la vida.",
  "Inferior": "Temor crónico de poseer menos valor, habilidades o estatus que los demás, afectando negativamente el autoconcepto.",
  "Insuficiente": "Miedo a no cumplir con los estándares requeridos o expectativas ajenas, sintiendo que uno nunca 'es suficiente'.",
  "Sumisión": "Comportamiento de subordinación derivado del miedo a las represalias, el rechazo o el abandono, cediendo el propio poder.",
  "Insignificante": "Percepción temerosa de la propia carencia de importancia, influencia o peso en el entorno relacional.",
  "Inútil": "Sentimiento de ineptitud y miedo a ser desechado por no poder aportar valor, competencia o utilidad a los demás.",
  "Rechazo": "Miedo fundamental a ser excluido de un grupo o relación significativa, amenazando la necesidad biológica de pertenencia.",
  "Alienación": "Temor prolongado y doloroso de no encajar en ningún lugar, experimentando desconexión social y emocional del entorno.",
  "Marginación": "Miedo a ser activamente desplazado, ignorado o empujado hacia los bordes de la dinámica social o grupal.",
  "Humillación": "Miedo paralizante a que la propia imagen social sea dañada públicamente o degradada de forma vergonzosa.",
  "Ridículo": "Temor a la burla y a la devaluación social al percibir que uno ha actuado de forma cómica involuntaria o inapropiada.",
  "Desprecio": "Miedo profundo a ser evaluado con asco social y desdén absoluto, considerándose indigno de respeto o valor mínimo.",
  "Sorpresa": "Emoción breve de alta activación en respuesta a estímulos novedosos, inesperados o inusuales.",
  "Sorprendido": "Estado neutro de alerta inicial provocado por un estímulo súbito que interrumpe la actividad actual.",
  "Conmoción": "Reacción intensa de parálisis cognitiva temporal ante una noticia o evento disruptivo e impactante.",
  "Alucinar": "Estado informal de incredulidad y asombro profundo ante algo que desafía fuertemente las propias expectativas.",
  "Confusión": "Estado de perplejidad cognitiva al no lograr integrar o entender inmediatamente la nueva información sorpresiva.",
  "Desilusión": "Choque emocional repentino al descubrir que una creencia o expectativa fundamental era falsa o errónea.",
  "Perplejidad": "Estado de duda, asombro y desorientación profunda ante algo paradójico, incomprensible o inesperado.",
  "Asombro": "Estado de reverencia y sorpresa prolongada ante algo percibido como inmenso, majestuoso o más grande que uno mismo.",
  "Estupefacción": "Reacción abrumadora de sorpresa que inmoviliza temporalmente la respuesta verbal o motora.",
  "Impresión": "Fuerte impacto psicológico o emocional duradero dejado por una experiencia novedosa y llamativa.",
  "Entusiasmo": "Sorpresa positiva y energizante motivada por el descubrimiento inesperado de algo excitante o beneficioso.",
  "Entusiasta": "Respuesta cálida, exaltada e inspirada hacia un estímulo inesperado que despierta alto interés o motivación.",
  "Enérgico": "Descarga de energía fisiológica y motora en respuesta a una novedad estimulante que invita a la acción rápida."
};

// Lista plana indexada: raíz → categorías → hojas, en orden determinístico.
// Usada por ai_service (prompt) y ai_processor (mapeo de índice → nombre exacto).
export const ALL_EMOTION_NAMES: string[] = [];
for (const root of Object.keys(EMOTIONS_HIERARCHY)) {
  ALL_EMOTION_NAMES.push(root);
  for (const cat of Object.keys(EMOTIONS_HIERARCHY[root])) {
    ALL_EMOTION_NAMES.push(cat);
    for (const leaf of EMOTIONS_HIERARCHY[root][cat]) {
      ALL_EMOTION_NAMES.push(leaf);
    }
  }
}
